import unittest

from day7.part1 import complete_manifold


class MyTestCase(unittest.TestCase):
    def test_something(self):
        diagram = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""
        split_count = complete_manifold(diagram)
        self.assertEqual(21, split_count)  # add assertion here


if __name__ == '__main__':
    unittest.main()
