import unittest

from day7.part2 import count_timelines


class MyTestCase(unittest.TestCase):
    def test_something(self):
        diagram = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""
        timelines = count_timelines(diagram)
        self.assertEqual(40, timelines)  # add assertion here


if __name__ == '__main__':
    unittest.main()
